name: 'Transform image'
on:
  push:
    branches:
    - main
    paths:
    - 'src/jupyter-pytorch/**'
  workflow_dispatch:

env:
  TARGET_REGISTORY: registry.cn-hangzhou.aliyuncs.com
  TARGET_NAMESPACE: linuzb
  SOURCE_REGISTORY: quay.io
  SOURCE_NAMESPACE: jupyter
  SOURCE_IMAGE: pytorch-notebook
  SOURCE_TAG: cuda11-pytorch-2.2.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          echo "1 Free space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
          echo "2 Free space:"
          df -h

      # git checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Use the git command to retrieve the current tag information and store it in the environment variable APP_VERSION.
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.TARGET_REGISTORY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and push
        id: docker_build_
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/jupyter-pytorch/Dockerfile
          # docker build arg
          build-args: |
            BASE_IMATE=${{ env.SOURCE_REGISTORY }}/${{ env.SOURCE_NAMESPACE }}/${{ env.SOURCE_IMAGE }}:${{ env.SOURCE_TAG }}
          tags: |
            ${{ env.TARGET_REGISTORY }}/${{ env.TARGET_NAMESPACE }}/${{ env.SOURCE_IMAGE }}:${{ env.SOURCE_TAG }}-${{ env.APP_VERSION }}
